//! OAuth account requests: Data API v3 for library, TV API for history and discovery.
//!
//! Music web-client OAuth requests can fail while TV-client requests work. The
//! official Data API supports library operations with the
//! same device-flow token. The user's playlists and liked videos live
//! here; search and playback stay on their existing paths.
//!
//! Quota: the default 10,000 daily units cost 1 per page here, so a
//! library load spends a handful.

use serde_json::Value;
use tokio::sync::RwLock;

use crate::core::model::{ArtistId, ArtistRef, Playlist, PlaylistId, Track, TrackId};

const BASE: &str = "https://www.googleapis.com/youtube/v3";
/// The autogenerated playlist of liked videos. Songs liked in
/// YouTube Music land here too.
const LIKED_VIDEOS_PLAYLIST: &str = "LL";
/// A liked list can hold thousands of entries (one user: 4875 songs).
/// Pages stream to the caller as they arrive, so the cap only bounds
/// the total, not how soon the first row shows. Quota: 2 units per
/// page (one list call, one duration call), so 100 pages cost 200 of
/// the 10,000 daily units. One hundred pages, 5000 tracks, cover the
/// user's full liked list.
const LIKED_PAGE_CAP: usize = 100;
const NO_PAGE_CAP: usize = usize::MAX;

pub struct DataApi {
    http: reqwest::Client,
    token: RwLock<ytmapi_rs::auth::OAuthToken>,
    refresh_client: ytmapi_rs::Client,
    auth_expired: std::sync::atomic::AtomicBool,
}

impl DataApi {
    pub fn new(token: ytmapi_rs::auth::OAuthToken) -> Result<Self, String> {
        let http = reqwest::Client::builder()
            .timeout(std::time::Duration::from_secs(15))
            .build()
            .map_err(|_| "Couldn’t create a network connection.".to_owned())?;
        Ok(Self {
            refresh_client: ytmapi_rs::Client::new_from_reqwest_client(http.clone()),
            http,
            token: RwLock::new(token),
            auth_expired: std::sync::atomic::AtomicBool::new(false),
        })
    }
    pub fn needs_sign_in(&self) -> bool {
        self.auth_expired.load(std::sync::atomic::Ordering::Relaxed)
    }
    pub async fn verify_account(&self) -> Result<(), String> {
        self.send_with_retry(|http, token| {
            http.get(format!("{BASE}/playlists?part=id&mine=true&maxResults=1"))
                .bearer_auth(token)
        })
        .await
        .map(|_| ())
    }

    pub async fn discovery(
        &self,
        target: &crate::core::discovery::Target,
        continuation: Option<String>,
    ) -> Result<crate::core::discovery::FeedPage, String> {
        use crate::core::discovery::Target;
        let mut body = serde_json::json!({"context":{"client":{"clientName":"TVHTML5","clientVersion":"7.20240925.00.00","hl":"en","gl":"US"}}});
        let endpoint = match target {
            Target::Browse { id, params } => {
                body["browseId"] = id.clone().into();
                if let Some(params) = params {
                    body["params"] = params.clone().into();
                }
                "browse"
            }
            Target::Watch {
                video,
                playlist,
                params,
            } => {
                if let Some(video) = video {
                    body["videoId"] = video.clone().into();
                }
                if let Some(playlist) = playlist {
                    body["playlistId"] = playlist.clone().into();
                }
                if let Some(params) = params {
                    body["params"] = params.clone().into();
                }
                "next"
            }
        };
        if let Some(continuation) = continuation {
            body = serde_json::json!({"context":body["context"],"continuation":continuation});
        }
        let value = self
            .send_with_retry(|http, token| {
                http.post(format!("https://www.youtube.com/youtubei/v1/{endpoint}"))
                    .bearer_auth(token)
                    .header(
                        "User-Agent",
                        "Mozilla/5.0 (ChromiumStylePlatform) Cobalt/Version",
                    )
                    .timeout(std::time::Duration::from_secs(15))
                    .json(&body)
            })
            .await?;
        if let Target::Watch {
            playlist: Some(playlist),
            ..
        } = target
        {
            super::discovery::parse_radio(&value, playlist)
        } else {
            super::discovery::parse(&value)
        }
    }

    pub async fn history(
        &self,
        continuation: Option<String>,
    ) -> Result<crate::core::listening_history::HistoryPage, String> {
        let mut body = serde_json::json!({"context":{"client":{"clientName":"TVHTML5","clientVersion":"7.20240925.00.00","hl":"en","gl":"US"}}});
        if let Some(continuation) = continuation {
            body["continuation"] = Value::String(continuation);
        } else {
            body["browseId"] = Value::String("FEhistory".into());
        }
        let value = self
            .send_with_retry(|http, token| {
                http.post("https://www.youtube.com/youtubei/v1/browse")
                    .bearer_auth(token)
                    .header(
                        "User-Agent",
                        "Mozilla/5.0 (ChromiumStylePlatform) Cobalt/Version",
                    )
                    .header("Content-Type", "application/json")
                    .timeout(std::time::Duration::from_secs(15))
                    .body(body.to_string())
            })
            .await?;
        super::history::parse(&value)
    }

    pub async fn playlists(&self) -> Result<Vec<Playlist>, String> {
        let url = format!("{BASE}/playlists?part=snippet,contentDetails&mine=true&maxResults=50");
        let pages = self.get_pages(&url, NO_PAGE_CAP).await?;
        Ok(pages
            .iter()
            .flat_map(items_of)
            .map(parse_playlist)
            .collect())
    }

    /// Streams the liked-songs list to `on_page`, one page of up to 50
    /// tracks at a time. The final call carries `finished: true`.
    pub async fn liked_songs(&self, on_page: impl FnMut(Vec<Track>, bool)) -> Result<(), String> {
        self.tracks_of(LIKED_VIDEOS_PLAYLIST, LIKED_PAGE_CAP, on_page)
            .await
    }

    /// Streams a playlist's tracks to `on_page`, the same way as
    /// [`Self::liked_songs`].
    pub async fn playlist_tracks(
        &self,
        id: &PlaylistId,
        on_page: impl FnMut(Vec<Track>, bool),
    ) -> Result<(), String> {
        self.tracks_of(&id.0, NO_PAGE_CAP, on_page).await
    }

    /// Likes or unlikes a video. The like state is a rating, not a
    /// resource: 204 with no body on success.
    pub async fn rate_video(&self, id: &TrackId, liked: bool) -> Result<(), String> {
        let url = format!("{BASE}{}", rate_path(id, liked));
        self.post_json(&url, serde_json::json!({})).await?;
        Ok(())
    }

    /// Adds one track to a playlist and returns the new row's item
    /// id, for a later removal.
    pub async fn insert_playlist_item(
        &self,
        playlist_id: &PlaylistId,
        track_id: &TrackId,
    ) -> Result<String, String> {
        let url = format!("{BASE}/playlistItems?part=snippet");
        let body = playlist_item_body(playlist_id, track_id);
        let response = self.post_json(&url, body).await?;
        item_id_of(&response)
    }

    /// Removes one row from a playlist by its item id.
    pub async fn delete_playlist_item(&self, item_id: &str) -> Result<(), String> {
        let url = format!("{BASE}/playlistItems?id={item_id}");
        self.delete(&url).await
    }

    /// Creates a private playlist and returns it.
    pub async fn insert_playlist(&self, title: &str) -> Result<Playlist, String> {
        let url = format!("{BASE}/playlists?part=snippet,status");
        let body = playlist_body(title);
        let response = self.post_json(&url, body).await?;
        Ok(parse_playlist(&response))
    }

    /// Deletes a playlist the user owns.
    pub async fn delete_playlist(&self, id: &PlaylistId) -> Result<(), String> {
        let url = format!("{BASE}/playlists?id={}", id.0);
        self.delete(&url).await
    }

    /// Fetches one page, fills its durations, and hands it to
    /// `on_page`, until the listing ends or `page_cap` is reached. A
    /// mid-stream error ends the stream after the pages already
    /// delivered; the pages themselves never reach the caller broken.
    async fn tracks_of(
        &self,
        playlist_id: &str,
        page_cap: usize,
        mut on_page: impl FnMut(Vec<Track>, bool),
    ) -> Result<(), String> {
        let url =
            format!("{BASE}/playlistItems?part=snippet&playlistId={playlist_id}&maxResults=50");
        let mut page_token = String::new();
        let mut pages_seen = 0;
        loop {
            let page = self.get_json(&paged_url(&url, &page_token)).await?;
            let mut tracks: Vec<Track> = items_of(&page).filter_map(parse_playlist_item).collect();
            self.fill_durations(&mut tracks).await;
            page_token = next_page_token(&page);
            pages_seen += 1;
            let finished = page_token.is_empty() || pages_seen >= page_cap;
            on_page(tracks, finished);
            if finished {
                return Ok(());
            }
        }
    }

    /// Durations come from a second endpoint, in batches of 50 ids.
    /// A failure here degrades to missing durations, not an error.
    async fn fill_durations(&self, tracks: &mut [Track]) {
        for batch in tracks.chunks_mut(50) {
            let ids: Vec<&str> = batch.iter().map(|track| track.id.0.as_str()).collect();
            let url = format!("{BASE}/videos?part=contentDetails&id={}", ids.join(","));
            match self.get_json(&url).await {
                Ok(page) => apply_durations(batch, &page),
                Err(error) => {
                    log::warn!("duration lookup failed: {error}");
                    return;
                }
            }
        }
    }

    /// Follows nextPageToken until the listing ends or the cap hits,
    /// and collects every page. Used only where the whole listing is
    /// small and safe to hold in memory before it is returned.
    async fn get_pages(&self, url: &str, page_cap: usize) -> Result<Vec<Value>, String> {
        let mut pages = Vec::new();
        let mut page_token = String::new();
        loop {
            let page = self.get_json(&paged_url(url, &page_token)).await?;
            page_token = next_page_token(&page);
            pages.push(page);
            if page_token.is_empty() || pages.len() >= page_cap {
                return Ok(pages);
            }
        }
    }

    /// One GET with the bearer token.
    async fn get_json(&self, url: &str) -> Result<Value, String> {
        self.send_with_retry(|http, token| http.get(url).bearer_auth(token))
            .await
    }

    /// One POST with the bearer token and a JSON body.
    async fn post_json(&self, url: &str, body: Value) -> Result<Value, String> {
        self.send_with_retry(|http, token| http.post(url).bearer_auth(token).json(&body))
            .await
    }

    /// One DELETE with the bearer token. A 204 with no body counts
    /// as success.
    async fn delete(&self, url: &str) -> Result<(), String> {
        self.send_with_retry(|http, token| http.delete(url).bearer_auth(token))
            .await?;
        Ok(())
    }

    /// Sends the request `build` describes, over the current bearer
    /// token. A 401 refreshes the token once and retries with the
    /// fresh one; `build` runs again for that retry, so it borrows
    /// its inputs rather than consuming them.
    async fn send_with_retry(
        &self,
        build: impl Fn(&reqwest::Client, &str) -> reqwest::RequestBuilder,
    ) -> Result<Value, String> {
        let first = self.send_with_current_token(&build).await?;
        if first.status() != reqwest::StatusCode::UNAUTHORIZED {
            return parse_response(first).await;
        }
        self.refresh_token().await?;
        let second = self.send_with_current_token(&build).await?;
        if second.status() == reqwest::StatusCode::UNAUTHORIZED {
            self.auth_expired
                .store(true, std::sync::atomic::Ordering::Relaxed);
        }
        parse_response(second).await
    }

    async fn send_with_current_token(
        &self,
        build: &impl Fn(&reqwest::Client, &str) -> reqwest::RequestBuilder,
    ) -> Result<reqwest::Response, String> {
        let access_token = access_token_of(&*self.token.read().await)?;
        build(&self.http, &access_token)
            .send()
            .await
            .map_err(|error| format!("The request failed: {error}"))
    }

    async fn refresh_token(&self) -> Result<(), String> {
        let mut token = self.token.write().await;
        let fresh = token.refresh(&self.refresh_client).await.map_err(|error| {
            let message = error.to_string();
            if crate::core::sign_in::SignInFailure::classify(&message)
                == crate::core::sign_in::SignInFailure::Expired
            {
                self.auth_expired
                    .store(true, std::sync::atomic::Ordering::Relaxed);
            }
            format!("The OAuth refresh failed: {message}")
        })?;
        if let Ok(json) = serde_json::to_string(&fresh)
            && let Err(error) = crate::auth::save_oauth_token(&json)
        {
            log::warn!("could not persist the refreshed OAuth token: {error}");
        }
        *token = fresh;
        Ok(())
    }
}

/// The access token, read through serde because the field is private.
fn access_token_of(token: &ytmapi_rs::auth::OAuthToken) -> Result<String, String> {
    serde_json::to_value(token)
        .ok()
        .and_then(|value| value.get("access_token")?.as_str().map(String::from))
        .ok_or("The OAuth token carries no access token.".to_string())
}

async fn parse_response(response: reqwest::Response) -> Result<Value, String> {
    let status = response.status();
    if status == reqwest::StatusCode::NO_CONTENT {
        return Ok(Value::Null);
    }
    let body: Value = response
        .json()
        .await
        .map_err(|error| format!("The response does not parse: {error}"))?;
    if let Some(error) = body.get("error") {
        let message = error
            .get("message")
            .and_then(Value::as_str)
            .unwrap_or("unknown");
        return Err(format!("YouTube answered {status}: {message}"));
    }
    if !status.is_success() {
        return Err(format!("YouTube answered {status}"));
    }
    Ok(body)
}

/// `url` with `page_token` appended as a `pageToken` parameter, or
/// `url` unchanged for the first page, when the token is empty.
fn paged_url(url: &str, page_token: &str) -> String {
    if page_token.is_empty() {
        return url.to_string();
    }
    format!("{url}&pageToken={page_token}")
}

/// The token for the next page, or an empty string at the last page.
fn next_page_token(page: &Value) -> String {
    page.get("nextPageToken")
        .and_then(Value::as_str)
        .unwrap_or_default()
        .to_string()
}

fn items_of(page: &Value) -> impl Iterator<Item = &Value> {
    page.get("items")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
}

/// The path and query for a like or unlike request against one video.
fn rate_path(id: &TrackId, liked: bool) -> String {
    let rating = if liked { "like" } else { "none" };
    format!("/videos/rate?id={}&rating={rating}", id.0)
}

/// The body of a `playlistItems.insert` request: the video's place in
/// the playlist.
fn playlist_item_body(playlist_id: &PlaylistId, track_id: &TrackId) -> Value {
    serde_json::json!({
        "snippet": {
            "playlistId": playlist_id.0,
            "resourceId": {
                "kind": "youtube#video",
                "videoId": track_id.0,
            }
        }
    })
}

/// The body of a `playlists.insert` request: a private playlist with
/// this title.
fn playlist_body(title: &str) -> Value {
    serde_json::json!({
        "snippet": {"title": title},
        "status": {"privacyStatus": "private"}
    })
}

/// The `id` field of a write response, the new resource's id.
fn item_id_of(value: &Value) -> Result<String, String> {
    value
        .get("id")
        .and_then(Value::as_str)
        .map(str::to_string)
        .ok_or_else(|| "The write response carried no id.".to_string())
}

fn parse_playlist(item: &Value) -> Playlist {
    Playlist {
        id: PlaylistId(text_of(item, "/id")),
        title: text_of(item, "/snippet/title"),
        track_count: item
            .pointer("/contentDetails/itemCount")
            .and_then(Value::as_u64)
            .map(|n| n as usize),
        thumbnail_url: thumbnail_of(item),
    }
}

/// Deleted and private videos stay in playlists as stubs with no
/// channel; they disappear from the list.
fn parse_playlist_item(item: &Value) -> Option<Track> {
    let video_id = item
        .pointer("/snippet/resourceId/videoId")?
        .as_str()?
        .to_string();
    item.pointer("/snippet/videoOwnerChannelTitle")?;
    Some(Track {
        id: TrackId(video_id),
        title: text_of(item, "/snippet/title"),
        artists: vec![video_owner_artist(item)],
        album: None,
        album_id: None,
        duration: None,
        thumbnail_url: thumbnail_of(item),
        playlist_item_id: Some(text_of(item, "/id")),
    })
}

/// The uploading channel as an artist credit. The channel id is
/// absent for some items, so the name alone still shows.
fn video_owner_artist(item: &Value) -> ArtistRef {
    let name = display_channel_title(&text_of(item, "/snippet/videoOwnerChannelTitle"));
    let id = item
        .pointer("/snippet/videoOwnerChannelId")
        .and_then(Value::as_str)
        .map(|id| ArtistId(id.to_string()));
    ArtistRef { name, id }
}

/// Strips the auto-generated " - Topic" suffix a music channel's
/// title carries, so the artist label reads as a plain name.
fn display_channel_title(title: &str) -> String {
    title.strip_suffix(" - Topic").unwrap_or(title).to_string()
}

fn apply_durations(tracks: &mut [Track], page: &Value) {
    for item in items_of(page) {
        let id = item.get("id").and_then(Value::as_str).unwrap_or_default();
        let duration = item
            .pointer("/contentDetails/duration")
            .and_then(Value::as_str)
            .and_then(parse_iso8601_duration);
        if let Some(track) = tracks.iter_mut().find(|track| track.id.0 == id) {
            track.duration = duration;
        }
    }
}

/// Parses the API's ISO 8601 durations: PT3M45S, PT1H2M3S, PT45S.
fn parse_iso8601_duration(text: &str) -> Option<std::time::Duration> {
    let body = text.strip_prefix("PT")?;
    let mut seconds: u64 = 0;
    let mut number = String::new();
    for character in body.chars() {
        if character.is_ascii_digit() {
            number.push(character);
            continue;
        }
        let value: u64 = number.parse().ok()?;
        number.clear();
        seconds += match character {
            'H' => value * 3600,
            'M' => value * 60,
            'S' => value,
            _ => return None,
        };
    }
    Some(std::time::Duration::from_secs(seconds))
}

fn text_of(item: &Value, pointer: &str) -> String {
    item.pointer(pointer)
        .and_then(Value::as_str)
        .unwrap_or_default()
        .to_string()
}

fn thumbnail_of(item: &Value) -> Option<String> {
    for size in ["high", "medium", "default"] {
        let pointer = format!("/snippet/thumbnails/{size}/url");
        if let Some(url) = item.pointer(&pointer).and_then(Value::as_str) {
            return Some(url.to_string());
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::Duration;

    #[test]
    fn iso8601_durations_parse() {
        assert_eq!(
            parse_iso8601_duration("PT3M45S"),
            Some(Duration::from_secs(225))
        );
        assert_eq!(
            parse_iso8601_duration("PT1H2M3S"),
            Some(Duration::from_secs(3723))
        );
        assert_eq!(
            parse_iso8601_duration("PT45S"),
            Some(Duration::from_secs(45))
        );
        assert_eq!(parse_iso8601_duration("P1D"), None);
    }

    #[test]
    fn a_topic_channel_title_loses_its_suffix() {
        assert_eq!(display_channel_title("Radiohead - Topic"), "Radiohead");
        assert_eq!(display_channel_title("Radiohead"), "Radiohead");
    }

    #[test]
    fn playlist_items_without_a_channel_are_stubs() {
        let stub = serde_json::json!({"snippet": {"resourceId": {"videoId": "abc"}, "title": "Deleted video"}});
        assert_eq!(parse_playlist_item(&stub), None);
    }

    #[test]
    fn rate_path_carries_the_video_id_and_rating() {
        let id = TrackId("abc".into());
        assert_eq!(rate_path(&id, true), "/videos/rate?id=abc&rating=like");
        assert_eq!(rate_path(&id, false), "/videos/rate?id=abc&rating=none");
    }

    #[test]
    fn playlist_item_body_names_the_playlist_and_the_video() {
        let body = playlist_item_body(&PlaylistId("PL1".into()), &TrackId("v1".into()));
        assert_eq!(body["snippet"]["playlistId"], "PL1");
        assert_eq!(body["snippet"]["resourceId"]["videoId"], "v1");
        assert_eq!(body["snippet"]["resourceId"]["kind"], "youtube#video");
    }

    #[test]
    fn playlist_body_is_private_with_the_given_title() {
        let body = playlist_body("My Mix");
        assert_eq!(body["snippet"]["title"], "My Mix");
        assert_eq!(body["status"]["privacyStatus"], "private");
    }

    #[test]
    fn item_id_of_reads_the_id_field() {
        let response = serde_json::json!({"id": "item-1"});
        assert_eq!(item_id_of(&response), Ok("item-1".to_string()));
        assert!(item_id_of(&serde_json::json!({})).is_err());
    }

    #[test]
    fn playlists_parse_from_the_official_shape() {
        let item = serde_json::json!({
            "id": "PL1",
            "snippet": {"title": "Mix", "thumbnails": {"high": {"url": "u"}}},
            "contentDetails": {"itemCount": 7}
        });
        let playlist = parse_playlist(&item);
        assert_eq!(playlist.id.0, "PL1");
        assert_eq!(playlist.title, "Mix");
        assert_eq!(playlist.track_count, Some(7));
        assert_eq!(playlist.thumbnail_url, Some("u".to_string()));
    }
}
