//! The official YouTube Data API v3, for account data under OAuth.
//!
//! Google broke OAuth against the internal API in 2025-08, but the
//! official API is a supported product and keeps working with the
//! same device-flow token. The user's playlists and liked videos live
//! here; search and playback stay on their existing paths.
//!
//! Quota: the default 10,000 daily units cost 1 per page here, so a
//! library load spends a handful.

use serde_json::Value;
use tokio::sync::RwLock;

use crate::core::model::{Playlist, PlaylistId, Track, TrackId};

const BASE: &str = "https://www.googleapis.com/youtube/v3";
/// The autogenerated playlist of liked videos. Songs liked in
/// YouTube Music land here too.
const LIKED_VIDEOS_PLAYLIST: &str = "LL";
/// A liked list can hold thousands of entries (one user: 4875 songs).
/// Pages stream to the caller as they arrive, so the cap only bounds
/// the total, not how soon the first row shows. Quota: 2 units per
/// page (one list call, one duration call), so 100 pages cost 200 of
/// the 10,000 daily units. One hundred pages, 5000 tracks, cover the
/// user's full liked list.
const LIKED_PAGE_CAP: usize = 100;
const NO_PAGE_CAP: usize = usize::MAX;

pub struct DataApi {
    http: reqwest::Client,
    token: RwLock<ytmapi_rs::auth::OAuthToken>,
    refresh_client: ytmapi_rs::Client,
}

impl DataApi {
    pub fn new(token: ytmapi_rs::auth::OAuthToken) -> Result<Self, String> {
        Ok(Self {
            http: reqwest::Client::new(),
            token: RwLock::new(token),
            refresh_client: ytmapi_rs::Client::new()
                .map_err(|error| format!("The HTTP client failed to build: {error}"))?,
        })
    }

    pub async fn playlists(&self) -> Result<Vec<Playlist>, String> {
        let url = format!("{BASE}/playlists?part=snippet,contentDetails&mine=true&maxResults=50");
        let pages = self.get_pages(&url, NO_PAGE_CAP).await?;
        Ok(pages
            .iter()
            .flat_map(items_of)
            .map(parse_playlist)
            .collect())
    }

    /// Streams the liked-songs list to `on_page`, one page of up to 50
    /// tracks at a time. The final call carries `finished: true`.
    pub async fn liked_songs(
        &self,
        on_page: impl FnMut(Vec<Track>, bool),
    ) -> Result<(), String> {
        self.tracks_of(LIKED_VIDEOS_PLAYLIST, LIKED_PAGE_CAP, on_page)
            .await
    }

    /// Streams a playlist's tracks to `on_page`, the same way as
    /// [`Self::liked_songs`].
    pub async fn playlist_tracks(
        &self,
        id: &PlaylistId,
        on_page: impl FnMut(Vec<Track>, bool),
    ) -> Result<(), String> {
        self.tracks_of(&id.0, NO_PAGE_CAP, on_page).await
    }

    /// Fetches one page, fills its durations, and hands it to
    /// `on_page`, until the listing ends or `page_cap` is reached. A
    /// mid-stream error ends the stream after the pages already
    /// delivered; the pages themselves never reach the caller broken.
    async fn tracks_of(
        &self,
        playlist_id: &str,
        page_cap: usize,
        mut on_page: impl FnMut(Vec<Track>, bool),
    ) -> Result<(), String> {
        let url =
            format!("{BASE}/playlistItems?part=snippet&playlistId={playlist_id}&maxResults=50");
        let mut page_token = String::new();
        let mut pages_seen = 0;
        loop {
            let page = self.get_json(&paged_url(&url, &page_token)).await?;
            let mut tracks: Vec<Track> = items_of(&page).filter_map(parse_playlist_item).collect();
            self.fill_durations(&mut tracks).await;
            page_token = next_page_token(&page);
            pages_seen += 1;
            let finished = page_token.is_empty() || pages_seen >= page_cap;
            on_page(tracks, finished);
            if finished {
                return Ok(());
            }
        }
    }

    /// Durations come from a second endpoint, in batches of 50 ids.
    /// A failure here degrades to missing durations, not an error.
    async fn fill_durations(&self, tracks: &mut [Track]) {
        for batch in tracks.chunks_mut(50) {
            let ids: Vec<&str> = batch.iter().map(|track| track.id.0.as_str()).collect();
            let url = format!("{BASE}/videos?part=contentDetails&id={}", ids.join(","));
            match self.get_json(&url).await {
                Ok(page) => apply_durations(batch, &page),
                Err(error) => {
                    log::warn!("duration lookup failed: {error}");
                    return;
                }
            }
        }
    }

    /// Follows nextPageToken until the listing ends or the cap hits,
    /// and collects every page. Used only where the whole listing is
    /// small and safe to hold in memory before it is returned.
    async fn get_pages(&self, url: &str, page_cap: usize) -> Result<Vec<Value>, String> {
        let mut pages = Vec::new();
        let mut page_token = String::new();
        loop {
            let page = self.get_json(&paged_url(url, &page_token)).await?;
            page_token = next_page_token(&page);
            pages.push(page);
            if page_token.is_empty() || pages.len() >= page_cap {
                return Ok(pages);
            }
        }
    }

    /// One GET with the bearer token. A 401 refreshes the token once
    /// and retries, then persists the fresh token for the next start.
    async fn get_json(&self, url: &str) -> Result<Value, String> {
        let first = self.get_with_current_token(url).await?;
        if first.status() != reqwest::StatusCode::UNAUTHORIZED {
            return parse_response(first).await;
        }
        self.refresh_token().await?;
        let second = self.get_with_current_token(url).await?;
        parse_response(second).await
    }

    async fn get_with_current_token(&self, url: &str) -> Result<reqwest::Response, String> {
        let access_token = access_token_of(&*self.token.read().await)?;
        self.http
            .get(url)
            .bearer_auth(access_token)
            .send()
            .await
            .map_err(|error| format!("The request failed: {error}"))
    }

    async fn refresh_token(&self) -> Result<(), String> {
        let mut token = self.token.write().await;
        let fresh = token
            .refresh(&self.refresh_client)
            .await
            .map_err(|error| format!("The OAuth refresh failed: {error}"))?;
        if let Ok(json) = serde_json::to_string(&fresh)
            && let Err(error) = crate::auth::save_oauth_token(&json)
        {
            log::warn!("could not persist the refreshed OAuth token: {error}");
        }
        *token = fresh;
        Ok(())
    }
}

/// The access token, read through serde because the field is private.
fn access_token_of(token: &ytmapi_rs::auth::OAuthToken) -> Result<String, String> {
    serde_json::to_value(token)
        .ok()
        .and_then(|value| value.get("access_token")?.as_str().map(String::from))
        .ok_or("The OAuth token carries no access token.".to_string())
}

async fn parse_response(response: reqwest::Response) -> Result<Value, String> {
    let status = response.status();
    let body: Value = response
        .json()
        .await
        .map_err(|error| format!("The response does not parse: {error}"))?;
    if let Some(error) = body.get("error") {
        let message = error
            .get("message")
            .and_then(Value::as_str)
            .unwrap_or("unknown");
        return Err(format!("YouTube answered {status}: {message}"));
    }
    Ok(body)
}

/// `url` with `page_token` appended as a `pageToken` parameter, or
/// `url` unchanged for the first page, when the token is empty.
fn paged_url(url: &str, page_token: &str) -> String {
    if page_token.is_empty() {
        return url.to_string();
    }
    format!("{url}&pageToken={page_token}")
}

/// The token for the next page, or an empty string at the last page.
fn next_page_token(page: &Value) -> String {
    page.get("nextPageToken")
        .and_then(Value::as_str)
        .unwrap_or_default()
        .to_string()
}

fn items_of(page: &Value) -> impl Iterator<Item = &Value> {
    page.get("items")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
}

fn parse_playlist(item: &Value) -> Playlist {
    Playlist {
        id: PlaylistId(text_of(item, "/id")),
        title: text_of(item, "/snippet/title"),
        track_count: item
            .pointer("/contentDetails/itemCount")
            .and_then(Value::as_u64)
            .map(|n| n as usize),
        thumbnail_url: thumbnail_of(item),
    }
}

/// Deleted and private videos stay in playlists as stubs with no
/// channel; they disappear from the list.
fn parse_playlist_item(item: &Value) -> Option<Track> {
    let video_id = item
        .pointer("/snippet/resourceId/videoId")?
        .as_str()?
        .to_string();
    item.pointer("/snippet/videoOwnerChannelTitle")?;
    Some(Track {
        id: TrackId(video_id),
        title: text_of(item, "/snippet/title"),
        artists: vec![text_of(item, "/snippet/videoOwnerChannelTitle")],
        album: None,
        duration: None,
        thumbnail_url: thumbnail_of(item),
    })
}

fn apply_durations(tracks: &mut [Track], page: &Value) {
    for item in items_of(page) {
        let id = item.get("id").and_then(Value::as_str).unwrap_or_default();
        let duration = item
            .pointer("/contentDetails/duration")
            .and_then(Value::as_str)
            .and_then(parse_iso8601_duration);
        if let Some(track) = tracks.iter_mut().find(|track| track.id.0 == id) {
            track.duration = duration;
        }
    }
}

/// Parses the API's ISO 8601 durations: PT3M45S, PT1H2M3S, PT45S.
fn parse_iso8601_duration(text: &str) -> Option<std::time::Duration> {
    let body = text.strip_prefix("PT")?;
    let mut seconds: u64 = 0;
    let mut number = String::new();
    for character in body.chars() {
        if character.is_ascii_digit() {
            number.push(character);
            continue;
        }
        let value: u64 = number.parse().ok()?;
        number.clear();
        seconds += match character {
            'H' => value * 3600,
            'M' => value * 60,
            'S' => value,
            _ => return None,
        };
    }
    Some(std::time::Duration::from_secs(seconds))
}

fn text_of(item: &Value, pointer: &str) -> String {
    item.pointer(pointer)
        .and_then(Value::as_str)
        .unwrap_or_default()
        .to_string()
}

fn thumbnail_of(item: &Value) -> Option<String> {
    for size in ["high", "medium", "default"] {
        let pointer = format!("/snippet/thumbnails/{size}/url");
        if let Some(url) = item.pointer(&pointer).and_then(Value::as_str) {
            return Some(url.to_string());
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::Duration;

    #[test]
    fn iso8601_durations_parse() {
        assert_eq!(
            parse_iso8601_duration("PT3M45S"),
            Some(Duration::from_secs(225))
        );
        assert_eq!(
            parse_iso8601_duration("PT1H2M3S"),
            Some(Duration::from_secs(3723))
        );
        assert_eq!(
            parse_iso8601_duration("PT45S"),
            Some(Duration::from_secs(45))
        );
        assert_eq!(parse_iso8601_duration("P1D"), None);
    }

    #[test]
    fn playlist_items_without_a_channel_are_stubs() {
        let stub = serde_json::json!({"snippet": {"resourceId": {"videoId": "abc"}, "title": "Deleted video"}});
        assert_eq!(parse_playlist_item(&stub), None);
    }

    #[test]
    fn playlists_parse_from_the_official_shape() {
        let item = serde_json::json!({
            "id": "PL1",
            "snippet": {"title": "Mix", "thumbnails": {"high": {"url": "u"}}},
            "contentDetails": {"itemCount": 7}
        });
        let playlist = parse_playlist(&item);
        assert_eq!(playlist.id.0, "PL1");
        assert_eq!(playlist.title, "Mix");
        assert_eq!(playlist.track_count, Some(7));
        assert_eq!(playlist.thumbnail_url, Some("u".to_string()));
    }
}
